//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upd8_Challenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADE
    {
        public CIDADE()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public int CidadeId { get; set; }
        public string CidadeName { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
