//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upd8_Challenge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTE
    {
        public int ClienteId { get; set; }
        [Display(Name = "Cliente")]
        public string ClienteName { get; set; }
        public string CPF { get; set; }
        [Display(Name = "Data Nasc.")]
        public System.DateTime Birth { get; set; }
        public string Sexo { get; set; }
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }
        public int EstadoId { get; set; }
        public int CidadeId { get; set; }
    
        public virtual CIDADE CIDADE { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
