//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upd8_Challenge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class upd8_testeEntities : DbContext
    {
        public upd8_testeEntities()
            : base("name=upd8_testeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CIDADE> CIDADE { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<ESTADO> ESTADO { get; set; }
    }
}
